
export const TOOL_ITEMS = {
    LINE: "LINE",
    RECTANGLE: "RECTANGLE",
    CIRCLE: "CIRCLE",
    ARROW: "ARROW",
    BRUSH: "BRUSH",
    ERASER: "ERASER",
    TEXT: "TEXT"
}

export const TOOL_ACTION_TYPES = {
    NONE: "NONE",
    DRAWING: "DRAWING",
    ERASING: "ERASING",
    WRITING: "WRITING"
}

export const BOARD_ACTIONS = {
    CHANGE_TOOL: "CHANGE_TOOL",
    DRAW_DOWN: "DRAW_DOWN",
    DRAW_MOVE: "DRAW_MOVE",
    DRAW_UP: "DRAW_UP",
    ERASE: "ERASE",
    CHANGE_TOOL_ACTION: "CHANGE_TOOL_ACTION",
    CHANGE_TEXT: "CHANGE_TEXT",
    UNDO: "UNDO",
    REDO: "REDO"
}

export const TOOLBOX_ACTIONS = {
    CHANGE_STROKE: "CHANGE_STROKE",
    CHANGE_FILL: "CHANGE_FILL",
    CHANGE_SIZE: "CHANGE_SIZE"
}

export const STROKE_TOOL_TYPE = [TOOL_ITEMS.LINE, TOOL_ITEMS.RECTANGLE, TOOL_ITEMS.CIRCLE, TOOL_ITEMS.ARROW, TOOL_ITEMS.BRUSH, TOOL_ITEMS.TEXT]
export const FILL_TOOL_TYPE = [TOOL_ITEMS.RECTANGLE, TOOL_ITEMS.CIRCLE]

export const COLORS = {
    BLACK: "#000000",
    RED: "#FF0000",
    GREEN: "#008000",
    BLUE: "#0000FF",
    ORANGE: "#FFA500",
    YELLOW: "#FFFF00",
    WHITE: "#FFFFFF"
}

export const SIZE_TOOL_TYPE = [TOOL_ITEMS.LINE, TOOL_ITEMS.RECTANGLE, TOOL_ITEMS.CIRCLE, TOOL_ITEMS.ARROW, TOOL_ITEMS.TEXT]
export const ArrowLength = 20

export const ELEMENT_ERASE_THRESHOLDS = 0.1